workflows:
  version: 2.1
  lint:
    jobs:
      - lint_app1
      - lint_app2

version: 2.1
jobs:
  lint_app1:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
        cd app1
        npm ci
        npm run lint
  lint_app2:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
        npm app2
        npm ci
        npm run lint